/**
 * API hooks for threats, countermeasures, personas and the analysis payload.
 *
 * One threat table: `/api/threats/` serves every scenario whatever it
 * targets (plan section 4.1). A scenario has `targets[]` (component, flow,
 * zone, boundary) or is `wholeSystem`. Countermeasures live at
 * `/api/countermeasures/` with their own `targets[]` (where the control
 * applies; empty means the whole system) and `implementedBy` (the components
 * that implement it).
 *
 * Query strings stay snake_case (lib/api.ts does not rewrite them); bodies
 * and responses are camelCase.
 */

import { useQuery, useMutation, useQueryClient, skipToken } from '@tanstack/react-query'
import { api } from '@/lib/api'
import { deleteWithWarnings } from './delete-warnings'
import type {
  AnalysisCountermeasure,
  AnalysisTarget,
  AnalysisThreat,
  AlsoMitigatesEntry,
  CountermeasureStatus,
  TargetType,
} from '@/features/dfd-editor/types/threat-analysis'
import type { TaxonomyEntry, ThreatAccessLevel, ThreatIntent } from '@/types/domain'
import type { Rating, RatingInputs, RatingLevel } from '@/types/risk'
import type { TriageStatus } from '@/types/triage'
import { componentKeys } from './components'
import { riskKeys } from './risks'
import { countermeasureUiId, threatUiId } from '../lib/threat-ids'

export {
  parseCountermeasureId,
  threatUiId,
  threatIdFromUiId,
  countermeasureUiId,
  countermeasureIdFromUiId,
} from '../lib/threat-ids'
export type { TargetType }

// Backend countermeasure status. Aliased directly to the frontend CountermeasureStatus
// type (rather than duplicated as a literal union) so the two can no longer drift --
// this duplication is what caused precogly/precogly#328.
type BackendCountermeasureStatus = CountermeasureStatus

// ============================================
// Targets
// ============================================

/** A target reference as written: `[{type, id}]`. */
export interface TargetRef {
  type: TargetType
  id: number
}

/** A target as the serializers read it: `[{type, id, name, blueprintId}]`. */
export interface ThreatTarget extends TargetRef {
  name: string | null
  blueprintId: number
}

export type ThreatStatusValue = 'exposed' | 'addressable' | 'mitigated'

// ============================================
// Threats (InstanceThreatSerializer)
// ============================================

export interface InstanceThreat {
  id: number
  threatModel: number
  number: number
  /** `T7` for number 7. */
  displayNumber: string
  wholeSystem: boolean
  targets: ThreatTarget[]
  autoGenerated: boolean
  threatLibrary: number | null
  /** The name shown: the threat's own name, else the library's. */
  threatNameDisplay: string | null
  taxonomyEntries?: TaxonomyEntry[]
  rating: Rating | null
  businessObjectiveIds?: number[]
  businessObjectives: Array<{ id: number; name: string }>
  status: ThreatStatusValue
  triageStatus: TriageStatus
  decisionRationale: string
  formatMetadata: Record<string, unknown>
  displayOrder: number
  impactDescription?: string
  // One actor rule: a persona of the model or free text, never both
  actorPersona: number | null
  actorPersonaName: string | null
  threatActorText?: string
  intent: ThreatIntent | ''
  accessLevel: ThreatAccessLevel | ''
  threatSources?: { id: number; name: string; slug?: string }[]
  createdAt: string
  updatedAt: string
}

export interface CreateThreatInput {
  threatModel: number | string
  /** Required unless `wholeSystem` is true. */
  targets?: TargetRef[]
  wholeSystem?: boolean
  threatLibrary?: number | null
  threatName?: string
  threatDescription?: string
  /** A level alone, or the matrix inputs; omitted means a medium level-only rating. */
  ratingInputs?: RatingInputs
  status?: ThreatStatusValue
  triageStatus?: TriageStatus
  decisionRationale?: string
  impactDescription?: string
  actorPersona?: number | null
  threatActorText?: string
  businessObjectiveIds?: number[]
  intent?: ThreatIntent | ''
  accessLevel?: ThreatAccessLevel | ''
  displayOrder?: number
}

export type UpdateThreatInput = Partial<Omit<CreateThreatInput, 'threatModel'>>

export interface ThreatFilters {
  threatModel?: number | string
  blueprint?: number
  component?: number
  flow?: number
  zone?: number
  boundary?: number
  threatLibrary?: number
  status?: ThreatStatusValue
  triageStatus?: TriageStatus
  level?: RatingLevel
  number?: number
  wholeSystem?: boolean
  /** Matches the name, and `T7` or `7` the number. */
  search?: string
  ordering?: string
}

function threatQueryString(filters: ThreatFilters): string {
  const params = new URLSearchParams()
  if (filters.threatModel !== undefined) params.set('threat_model', String(filters.threatModel))
  if (filters.blueprint !== undefined) params.set('blueprint', String(filters.blueprint))
  if (filters.component !== undefined) params.set('component', String(filters.component))
  if (filters.flow !== undefined) params.set('flow', String(filters.flow))
  if (filters.zone !== undefined) params.set('zone', String(filters.zone))
  if (filters.boundary !== undefined) params.set('boundary', String(filters.boundary))
  if (filters.threatLibrary !== undefined) params.set('threat_library', String(filters.threatLibrary))
  if (filters.status) params.set('status', filters.status)
  if (filters.triageStatus) params.set('triage_status', filters.triageStatus)
  if (filters.level) params.set('rating__level', filters.level)
  if (filters.number !== undefined) params.set('number', String(filters.number))
  if (filters.wholeSystem !== undefined) params.set('whole_system', filters.wholeSystem ? 'true' : 'false')
  if (filters.search) params.set('search', filters.search)
  if (filters.ordering) params.set('ordering', filters.ordering)
  return params.toString()
}

export interface CountermeasureLibraryItem {
  id: number
  name: string
  description?: string
  controlFunctions: string[]
  controlNature: string
  cost: string
  defaultStatus?: string
  sourcePackName: string | null
  sourcePackSlug: string | null
}

export interface ThreatLibraryItem {
  id: number
  name: string
  description?: string  // Optional for defensive programming
  taxonomyEntries?: TaxonomyEntry[]
  sourcePackName: string | null
  sourcePackSlug: string | null
}

// ============================================
// Countermeasures (InstanceCountermeasureSerializer)
// ============================================

export interface CountermeasureThreatLink {
  id: number
  threatId: number
  displayNumber: string
  threatName: string | null
  targets: ThreatTarget[]
  displayOrder: number
}

export interface InstanceCountermeasure {
  id: number
  threatModel: number | string
  countermeasureLibrary: number | null
  countermeasureNameDisplay: string | null
  controlFunctionsDisplay: string[]
  controlNatureDisplay: string
  /** 0 to 1, or null for "not assessed". */
  effectiveness: number | null
  status: BackendCountermeasureStatus
  priority: string
  dueDate?: string | null
  externalTicketUrl?: string
  verifiedBy: number | null
  verifiedByEmail: string | null
  evidenceUrl: string
  requiredForRelease: boolean
  assignedOwner: number | null
  assignedOwnerEmail: string | null
  formatMetadata: Record<string, unknown>
  threatLinks: CountermeasureThreatLink[]
  autoGenerated: boolean
  number: number
  /** `C3` for number 3. */
  displayNumber: string
  daysOverdue: number | null
  /** Where the control applies; empty means the whole system. */
  targets: ThreatTarget[]
  /** Components that implement it. */
  implementedBy: number[]
  implementedByParty: string
  /** Where the control came from (free text). */
  source: string
  createdAt: string
  updatedAt: string
}

export interface CreateCountermeasureInput {
  threatModel: number | string
  /** Link the new control to this scenario. */
  threatId?: number
  countermeasureLibrary?: number | null
  countermeasureName?: string
  countermeasureDescription?: string
  controlFunctions?: string[]
  controlNature?: string
  status?: BackendCountermeasureStatus
  priority?: string
  dueDate?: string | null
  externalTicketUrl?: string
  evidenceUrl?: string
  requiredForRelease?: boolean
  assignedOwner?: number | null
  effectiveness?: number | null
  targets?: TargetRef[]
  implementedBy?: number[]
  implementedByParty?: string
  source?: string
}

export type UpdateCountermeasureInput = Partial<Omit<CreateCountermeasureInput, 'threatModel' | 'threatId'>> & {
  verifiedBy?: number | null
}

export interface CountermeasureFilters {
  threatModel?: number | string
  countermeasureLibrary?: number
  status?: BackendCountermeasureStatus
  requiredForRelease?: boolean
  number?: number
  /** Open controls past their due date. */
  overdue?: boolean
}

function countermeasureQueryString(filters: CountermeasureFilters): string {
  const params = new URLSearchParams()
  if (filters.threatModel !== undefined) params.set('threat_model', String(filters.threatModel))
  if (filters.countermeasureLibrary !== undefined) {
    params.set('countermeasure_library', String(filters.countermeasureLibrary))
  }
  if (filters.status) params.set('status', filters.status)
  if (filters.requiredForRelease !== undefined) {
    params.set('required_for_release', filters.requiredForRelease ? 'true' : 'false')
  }
  if (filters.number !== undefined) params.set('number', String(filters.number))
  if (filters.overdue) params.set('overdue', 'true')
  return params.toString()
}

export interface GenerateThreatsResponse {
  createdCount: number
  existingCount: number
  total: number
  message: string
}

/** POST /threat-models/{id}/generate-threats/ (plan L7). */
export interface GenerateModelThreatsResponse {
  created: number
  targets: number
}

export interface SuggestedCountermeasuresResponse {
  threatId: number
  threatName: string
  suggested: CountermeasureLibraryItem[]
  applied: CountermeasureLibraryItem[]
  suggestedCount: number
  appliedCount: number
}

export interface ApplyCountermeasureResponse {
  countermeasure: InstanceCountermeasure
  message: string
}

export interface RecalculateStatusResponse {
  threatId: number
  oldStatus: string
  newStatus: string
  message: string
}

// ============================================
// Query keys
// ============================================

export const threatKeys = {
  all: ['threats'] as const,
  list: (filters: ThreatFilters) => [...threatKeys.all, 'list', filters] as const,
  detail: (threatId: number) => [...threatKeys.all, 'detail', threatId] as const,
  suggestedCountermeasures: (threatId: number) => [...threatKeys.all, 'suggested', threatId] as const,
  threatLibrary: (componentId?: number | null, threatModelId?: string) =>
    componentId
      ? ['threat-library', componentId, threatModelId] as const
      : ['threat-library', threatModelId] as const,
  countermeasureLibrary: (threatModelId?: string) =>
    ['countermeasure-library', threatModelId] as const,
}

export const countermeasureKeys = {
  all: ['countermeasures'] as const,
  list: (filters: CountermeasureFilters) => [...countermeasureKeys.all, 'list', filters] as const,
  detail: (countermeasureId: number) => [...countermeasureKeys.all, 'detail', countermeasureId] as const,
  inUse: (threatModelId: string) => ['countermeasures-in-use', threatModelId] as const,
}

export const analysisKeys = {
  all: ['threat-model-threats'] as const,
  model: (threatModelId: string) => [...analysisKeys.all, threatModelId] as const,
}

export const personaKeys = {
  all: ['threat-personas'] as const,
  model: (threatModelId: string) => [...personaKeys.all, threatModelId] as const,
}

const instanceTaxonomyKeys = {
  all: ['threat-taxonomy'] as const,
  byThreat: (threatId: number) => [...instanceTaxonomyKeys.all, threatId] as const,
}

function invalidateThreatReaders(queryClient: ReturnType<typeof useQueryClient>) {
  queryClient.invalidateQueries({ queryKey: threatKeys.all })
  queryClient.invalidateQueries({ queryKey: analysisKeys.all })
  queryClient.invalidateQueries({ queryKey: ['threat-models'] })
}

function invalidateCountermeasureReaders(queryClient: ReturnType<typeof useQueryClient>) {
  invalidateThreatReaders(queryClient)
  queryClient.invalidateQueries({ queryKey: countermeasureKeys.all })
  queryClient.invalidateQueries({ queryKey: ['countermeasures-in-use'] })
  queryClient.invalidateQueries({ queryKey: riskKeys.all })
}

// ============================================
// Threat query hooks
// ============================================

/**
 * Threats matching the filters, from `/threats/`. Pass `enabled: false`
 * through `options` when the filter is not ready.
 */
export function useThreats(filters: ThreatFilters, options: { enabled?: boolean } = {}) {
  return useQuery({
    queryKey: threatKeys.list(filters),
    queryFn: async () => {
      const query = threatQueryString(filters)
      const response = await api.get<{ results: InstanceThreat[] } | InstanceThreat[]>(
        query ? `/threats/?${query}` : '/threats/'
      )
      return Array.isArray(response) ? response : response.results
    },
    enabled: options.enabled ?? true,
  })
}

export function useThreat(threatId: number | null) {
  return useQuery({
    queryKey: threatKeys.detail(threatId ?? -1),
    queryFn: threatId !== null ? () => api.get<InstanceThreat>(`/threats/${threatId}/`) : skipToken,
  })
}

/**
 * Fetch suggested countermeasures for a threat instance.
 */
export function useSuggestedCountermeasures(threatId: number | null) {
  return useQuery({
    queryKey: threatKeys.suggestedCountermeasures(threatId ?? -1),
    queryFn:
      threatId !== null
        ? () => api.get<SuggestedCountermeasuresResponse>(`/threats/${threatId}/suggested_countermeasures/`)
        : skipToken,
  })
}

/**
 * Fetch threats from the threat library.
 * Optionally filter by a component's library via component_id query param.
 * Optionally filter by connected packs via threat_model query param.
 */
export function useThreatLibrary(componentId?: number | null, threatModelId?: string) {
  return useQuery({
    queryKey: threatKeys.threatLibrary(componentId, threatModelId),
    queryFn: async () => {
      const params = new URLSearchParams()
      if (componentId) params.set('component_id', String(componentId))
      if (threatModelId) params.set('threat_model', threatModelId)
      const queryString = params.toString()
      const url = queryString ? `/threat-library/?${queryString}` : '/threat-library/'
      const response = await api.get<{ results: ThreatLibraryItem[] } | ThreatLibraryItem[]>(url)
      return Array.isArray(response) ? response : response.results
    },
  })
}

/**
 * Fetch all countermeasures from the countermeasure library.
 * Optionally filter by applicable threat library ID.
 * Optionally filter by connected packs via threat_model query param.
 */
export function useCountermeasureLibrary(threatLibraryId?: number | null, threatModelId?: string) {
  return useQuery({
    queryKey: [...threatKeys.countermeasureLibrary(threatModelId), threatLibraryId],
    queryFn: async () => {
      const params = new URLSearchParams()
      if (threatLibraryId) params.set('applicable_threats', String(threatLibraryId))
      if (threatModelId) params.set('threat_model', threatModelId)
      const queryString = params.toString()
      const url = queryString ? `/countermeasure-library/?${queryString}` : '/countermeasure-library/'
      const response = await api.get<{ results: CountermeasureLibraryItem[] } | CountermeasureLibraryItem[]>(url)
      return Array.isArray(response) ? response : response.results
    },
  })
}

// ============================================
// Threat mutation hooks
// ============================================

/**
 * Generate the library threats one component is missing
 * (`/components/{id}/generate_threats/`).
 */
export function useGenerateThreats() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (componentId: number) =>
      api.post<GenerateThreatsResponse>(`/components/${componentId}/generate_threats/`),
    onSuccess: () => invalidateThreatReaders(queryClient),
  })
}

/**
 * "Add missing library threats" for the whole model (plan L7). Threats
 * deleted earlier come back.
 */
export function useGenerateModelThreats() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (threatModelId: string) =>
      api.post<GenerateModelThreatsResponse>(`/threat-models/${threatModelId}/generate-threats/`),
    onSuccess: () => invalidateThreatReaders(queryClient),
  })
}

/**
 * Create a scenario on one or more targets, or a whole-system one.
 * From the library (threatLibrary set) or custom (threatLibrary null).
 */
export function useCreateThreat() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: CreateThreatInput) => api.post<InstanceThreat>('/threats/', data),
    onSuccess: () => invalidateThreatReaders(queryClient),
  })
}

/**
 * Update a scenario (status, rating inputs, actor, objectives, targets).
 */
export function useUpdateThreat() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ threatId, data }: { threatId: number; data: UpdateThreatInput }) =>
      api.patch<InstanceThreat>(`/threats/${threatId}/`, data),
    onSuccess: () => invalidateThreatReaders(queryClient),
  })
}

/**
 * Update the triage status of a scenario.
 */
export function useUpdateTriageStatus() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({
      threatId,
      triageStatus,
      decisionRationale,
    }: {
      threatId: number
      triageStatus: TriageStatus
      decisionRationale?: string
    }) =>
      api.patch<InstanceThreat>(`/threats/${threatId}/`, {
        triageStatus,
        decisionRationale: decisionRationale ?? '',
      }),
    onSuccess: () => invalidateThreatReaders(queryClient),
  })
}

/**
 * Replace a scenario's targets (`POST /threats/{id}/set_targets/`). An empty
 * list is refused unless `wholeSystem` is true (I8).
 */
export function useSetThreatTargets() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({
      threatId,
      targets,
      wholeSystem = false,
    }: {
      threatId: number
      targets: TargetRef[]
      wholeSystem?: boolean
    }) => api.post<InstanceThreat>(`/threats/${threatId}/set_targets/`, { targets, wholeSystem }),
    onSuccess: () => invalidateThreatReaders(queryClient),
  })
}

/**
 * Reorder scenarios. With `targetType` and `targetId` the order is per
 * target (what the tree shows under one node); otherwise it is the
 * scenario's own order within the model.
 */
export function useReorderThreats() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({
      orderedIds,
      targetType,
      targetId,
    }: {
      orderedIds: number[]
      targetType?: TargetType
      targetId?: number
    }) =>
      api.post('/threats/reorder/', {
        orderedIds,
        ...(targetType && targetId !== undefined && { targetType, targetId }),
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: analysisKeys.all })
    },
  })
}

export function useDeleteThreat() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (threatId: number) => api.delete(`/threats/${threatId}/`),
    onSuccess: () => {
      invalidateThreatReaders(queryClient)
      queryClient.invalidateQueries({ queryKey: riskKeys.all })
    },
  })
}

/**
 * Apply a countermeasure to a scenario: create one from the library, or link
 * an existing instance.
 */
export function useApplyCountermeasure() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({
      threatId,
      countermeasureLibraryId,
      existingCountermeasureId,
      status,
    }: {
      threatId: number
      countermeasureLibraryId?: number
      existingCountermeasureId?: number
      status?: string
    }) =>
      api.post<ApplyCountermeasureResponse>(`/threats/${threatId}/apply_countermeasure/`, {
        ...(countermeasureLibraryId && { countermeasureLibraryId }),
        ...(existingCountermeasureId && { existingCountermeasureId }),
        ...(status && { status }),
      }),
    onSuccess: (_, { threatId }) => {
      queryClient.invalidateQueries({ queryKey: threatKeys.suggestedCountermeasures(threatId) })
      invalidateCountermeasureReaders(queryClient)
    },
  })
}

/**
 * Recalculate threat status based on countermeasures.
 */
export function useRecalculateThreatStatus() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (threatId: number) =>
      api.post<RecalculateStatusResponse>(`/threats/${threatId}/recalculate_status/`),
    onSuccess: () => invalidateThreatReaders(queryClient),
  })
}

// ============================================
// Countermeasure hooks
// ============================================

export function useCountermeasures(filters: CountermeasureFilters, options: { enabled?: boolean } = {}) {
  return useQuery({
    queryKey: countermeasureKeys.list(filters),
    queryFn: async () => {
      const query = countermeasureQueryString(filters)
      const response = await api.get<{ results: InstanceCountermeasure[] } | InstanceCountermeasure[]>(
        query ? `/countermeasures/?${query}` : '/countermeasures/'
      )
      return Array.isArray(response) ? response : response.results
    },
    enabled: options.enabled ?? true,
  })
}

export function useCountermeasure(countermeasureId: number | null) {
  return useQuery({
    queryKey: countermeasureKeys.detail(countermeasureId ?? -1),
    queryFn:
      countermeasureId !== null
        ? () => api.get<InstanceCountermeasure>(`/countermeasures/${countermeasureId}/`)
        : skipToken,
  })
}

/**
 * Create a countermeasure instance, optionally linked to a scenario
 * (`threatId`) and scoped (`targets`).
 * From the library (countermeasureLibrary set) or custom (countermeasureLibrary null).
 */
export function useCreateCountermeasure() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: CreateCountermeasureInput) =>
      api.post<InstanceCountermeasure>('/countermeasures/', data),
    onSuccess: () => invalidateCountermeasureReaders(queryClient),
  })
}

/**
 * Update a countermeasure instance (status, evidence, scope, provider, source, effectiveness).
 */
export function useUpdateCountermeasure() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ countermeasureId, data }: { countermeasureId: number; data: UpdateCountermeasureInput }) =>
      api.patch<InstanceCountermeasure>(`/countermeasures/${countermeasureId}/`, data),
    onSuccess: () => invalidateCountermeasureReaders(queryClient),
  })
}

/**
 * Replace where a control applies (`POST /countermeasures/{id}/set_targets/`).
 * An empty list is allowed and means the whole system. Scope never changes a
 * threat's status (L4).
 */
export function useSetCountermeasureTargets() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ countermeasureId, targets }: { countermeasureId: number; targets: TargetRef[] }) =>
      api.post<InstanceCountermeasure>(`/countermeasures/${countermeasureId}/set_targets/`, { targets }),
    onSuccess: () => invalidateCountermeasureReaders(queryClient),
  })
}

export function useDeleteCountermeasure() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (countermeasureId: number) => api.delete(`/countermeasures/${countermeasureId}/`),
    onSuccess: () => invalidateCountermeasureReaders(queryClient),
  })
}

/**
 * Link an existing countermeasure to one more scenario.
 */
export function useLinkCountermeasure() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ countermeasureId, threatId }: { countermeasureId: number; threatId: number }) =>
      api.post<{ status: string; linkId: number }>(`/countermeasures/${countermeasureId}/link/`, { threatId }),
    onSuccess: () => invalidateCountermeasureReaders(queryClient),
  })
}

/**
 * Unlink a countermeasure from a scenario. An untouched generated control
 * that lost its last link is deleted; anything else stays and is listed as
 * unattached.
 */
export function useUnlinkCountermeasure() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ countermeasureId, threatId }: { countermeasureId: number; threatId: number }) =>
      api.post<{ status: 'unlinked' | 'deleted'; remainingLinks?: number; message?: string }>(
        `/countermeasures/${countermeasureId}/unlink/`,
        { threatId }
      ),
    onSuccess: () => invalidateCountermeasureReaders(queryClient),
  })
}

/**
 * Reorder the countermeasures shown under one scenario.
 */
export function useReorderCountermeasures() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ threatId, orderedIds }: { threatId: number; orderedIds: number[] }) =>
      api.post('/countermeasures/reorder/', { threatId, orderedIds }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: analysisKeys.all })
    },
  })
}

// ============================================
// Analysis payload: GET /threat-models/{id}/threats/
// (backend/apps/threat_models/analysis_service.py)
// ============================================

export interface NodeComponentMapEntry {
  componentId: number
  dfdId: string | null
  dfdName: string | null
  isAnalysisOnly?: boolean
}

export interface EdgeFlowMapEntry {
  flowId: number
  dfdId: string | null
  dfdName: string | null
  isAnalysisOnly?: boolean
}

export interface AnalysisStandardMapping {
  id: number
  frameworkName: string
  frameworkSlug: string
  sectionCode: string
  requirementDescription: string
  sufficiency: 'full' | 'partial'
}

/** One countermeasure entry of the analysis payload, as the backend sends it. */
export interface AnalysisPayloadCountermeasure {
  id: number
  countermeasureLibraryId: number | null
  countermeasureName: string | null
  countermeasureDescription: string | null
  controlFunctions: string[] | null
  controlNature: string | null
  status: BackendCountermeasureStatus
  priority: string
  dueDate?: string | null
  externalTicketUrl?: string
  evidenceUrl: string
  assignedOwnerEmail: string | null
  verifiedByEmail: string | null
  standardMappings: AnalysisStandardMapping[]
  displayOrder?: number
  autoGenerated: boolean
  number: number
  displayNumber: string
  targets: AnalysisTarget[]
  implementedBy: number[]
  implementedByParty: string
  source: string
  alsoMitigates?: AlsoMitigatesEntry[]
}

/** One threat entry of the analysis payload, as the backend sends it. */
export interface AnalysisPayloadThreat {
  id: number
  number: number
  displayNumber: string
  wholeSystem: boolean
  autoGenerated: boolean
  libraryMismatch: boolean
  targets: AnalysisTarget[]
  threatLibraryId: number | null
  threatName: string | null
  threatDescription: string | null
  taxonomyEntries?: TaxonomyEntry[]
  rating: Rating | null
  status: ThreatStatusValue
  triageStatus: TriageStatus
  decisionRationale: string
  displayOrder?: number
  impactDescription?: string
  threatActorText?: string
  actorPersonaId: number | null
  actorPersonaName: string | null
  intent: string
  accessLevel: string
  countermeasures: AnalysisPayloadCountermeasure[]
}

export interface ThreatAnalysisResponse {
  threatModelId: string
  threats: AnalysisPayloadThreat[]
  totalCount: number
  nodeComponentMap: Record<string, NodeComponentMapEntry>
  edgeFlowMap: Record<string, EdgeFlowMapEntry>
}

/** @deprecated Use `AnalysisPayloadThreat`. */
export type BackendThreat = AnalysisPayloadThreat
/** @deprecated Use `AnalysisPayloadCountermeasure`. */
export type BackendCountermeasure = AnalysisPayloadCountermeasure
/** @deprecated Use `AnalysisStandardMapping`. */
export type BackendStandardMapping = AnalysisStandardMapping

/**
 * Transform the analysis payload into the screen's `AnalysisThreat` shape.
 */
export function transformAnalysisThreats(payloadThreats: AnalysisPayloadThreat[]): AnalysisThreat[] {
  const now = new Date().toISOString()

  return payloadThreats.map((payloadThreat) => {
    const uiThreatId = threatUiId(payloadThreat.id)
    const firstTarget = payloadThreat.targets[0]

    const countermeasures: AnalysisCountermeasure[] = payloadThreat.countermeasures.map((cm) => ({
      id: countermeasureUiId(cm.id),
      countermeasureId: cm.countermeasureLibraryId ? `lib-${cm.countermeasureLibraryId}` : 'custom',
      componentThreatId: uiThreatId,
      status: cm.status as CountermeasureStatus,
      priority: (cm.priority || 'none') as AnalysisCountermeasure['priority'],
      dueDate: cm.dueDate ?? null,
      externalTicketUrl: cm.externalTicketUrl || undefined,
      owner: cm.assignedOwnerEmail || undefined,
      notes: cm.evidenceUrl || undefined,
      createdAt: now,
      updatedAt: now,
      backendCountermeasureId: cm.id,
      number: cm.number,
      displayNumber: cm.displayNumber,
      autoGenerated: cm.autoGenerated,
      targets: cm.targets ?? [],
      implementedBy: cm.implementedBy ?? [],
      implementedByParty: cm.implementedByParty || undefined,
      source: cm.source || undefined,
      countermeasureName: cm.countermeasureName || undefined,
      countermeasureDescription: cm.countermeasureDescription || undefined,
      controlFunctions: cm.controlFunctions || [],
      controlNature: cm.controlNature || '',
      standardMappings: cm.standardMappings || [],
      displayOrder: cm.displayOrder ?? 0,
      alsoMitigates: cm.alsoMitigates || [],
      isShared: (cm.alsoMitigates && cm.alsoMitigates.length > 0) || false,
    }))

    return {
      id: uiThreatId,
      diagramId: firstTarget?.dfdId || '',
      sourceDiagramId: firstTarget?.dfdId || undefined,
      sourceDiagramTitle: firstTarget?.dfdName || undefined,
      threatId: payloadThreat.threatLibraryId ? `lib-${payloadThreat.threatLibraryId}` : 'custom',
      triageStatus: payloadThreat.triageStatus || 'open',
      decisionRationale: payloadThreat.decisionRationale || '',
      countermeasures,
      createdAt: now,
      updatedAt: now,
      backendThreatId: payloadThreat.id,
      number: payloadThreat.number,
      displayNumber: payloadThreat.displayNumber,
      wholeSystem: payloadThreat.wholeSystem,
      targets: payloadThreat.targets ?? [],
      autoGenerated: payloadThreat.autoGenerated,
      libraryMismatch: payloadThreat.libraryMismatch,
      threatName: payloadThreat.threatName || undefined,
      threatDescription: payloadThreat.threatDescription || undefined,
      taxonomyEntries: payloadThreat.taxonomyEntries,
      rating: payloadThreat.rating,
      displayOrder: payloadThreat.displayOrder ?? 0,
      componentName: firstTarget?.name || undefined,
      impactDescription: payloadThreat.impactDescription || undefined,
      threatActorText: payloadThreat.threatActorText || undefined,
      actorPersonaId: payloadThreat.actorPersonaId,
      actorPersonaName: payloadThreat.actorPersonaName,
      intent: payloadThreat.intent || undefined,
      accessLevel: payloadThreat.accessLevel || undefined,
    }
  })
}

export interface ThreatAnalysisData extends ThreatAnalysisResponse {
  /** The payload's threats in the screen's shape. */
  analysisThreats: AnalysisThreat[]
}

/**
 * Fetch every scenario of a threat model with its countermeasures and canvas
 * placement (one payload builder, F29).
 */
export function useThreatModelThreats(threatModelId: string | null | undefined) {
  return useQuery({
    queryKey: analysisKeys.model(threatModelId ?? ''),
    queryFn: threatModelId
      ? async (): Promise<ThreatAnalysisData> => {
          const response = await api.get<ThreatAnalysisResponse>(`/threat-models/${threatModelId}/threats/`)
          return {
            ...response,
            analysisThreats: transformAnalysisThreats(response.threats),
          }
        }
      : skipToken,
    staleTime: 30000, // Consider fresh for 30 seconds
  })
}

// ============================================
// Countermeasures in use: GET /threat-models/{id}/countermeasures-in-use/
// ============================================

export interface CountermeasureInUse {
  id: number
  countermeasureName: string | null
  countermeasureLibraryId: number | null
  status: BackendCountermeasureStatus
  assignedOwnerEmail: string | null
  linkedThreats: Array<{
    threatId: number
    displayNumber: string
    threatName: string | null
    targets: ThreatTarget[]
  }>
}

interface CountermeasuresInUseResponse {
  threatModelId: string
  countermeasures: CountermeasureInUse[]
  totalCount: number
}

export function useCountermeasuresInUse(threatModelId: string | null | undefined) {
  return useQuery({
    queryKey: countermeasureKeys.inUse(threatModelId ?? ''),
    queryFn: threatModelId
      ? () => api.get<CountermeasuresInUseResponse>(`/threat-models/${threatModelId}/countermeasures-in-use/`)
      : skipToken,
    staleTime: 30000,
  })
}

export function useDeleteComponent() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (componentId: number) => deleteWithWarnings(`/components/${componentId}/`),
    onSuccess: () => {
      invalidateThreatReaders(queryClient)
      queryClient.invalidateQueries({ queryKey: componentKeys.all })
    },
  })
}

// ============================================
// Threat personas: /threat-models/{id}/threat-personas/ (plan J10)
// ============================================

export interface ThreatPersona {
  id: number
  threatModel: number
  symbolicName: string
  name: string
  description: string
  isPerson: boolean
  maliciousIntent: boolean
  skillLevel: string
  motivation: string
  resources: string
  objectives: string
  /** Threats citing the persona; shown before a delete. */
  threatCount?: number
  formatMetadata: Record<string, unknown>
  createdAt: string
  updatedAt: string
}

/** @deprecated Use `ThreatPersona`. */
export type ThreatPersonaItem = ThreatPersona

export interface CreateThreatPersonaInput {
  symbolicName: string
  name: string
  description?: string
  isPerson?: boolean
  maliciousIntent?: boolean
  skillLevel?: string
  motivation?: string
  resources?: string
  objectives?: string
}

export type UpdateThreatPersonaInput = Partial<CreateThreatPersonaInput>

export function useThreatPersonas(threatModelId: string | null | undefined) {
  return useQuery({
    queryKey: personaKeys.model(threatModelId ?? ''),
    queryFn: threatModelId
      ? () => api.get<ThreatPersona[]>(`/threat-models/${threatModelId}/threat-personas/`)
      : skipToken,
    staleTime: 5 * 60 * 1000,
  })
}

export function useCreateThreatPersona(threatModelId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: CreateThreatPersonaInput) =>
      api.post<ThreatPersona>(`/threat-models/${threatModelId}/threat-personas/`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: personaKeys.model(threatModelId) })
    },
  })
}

export function useUpdateThreatPersona(threatModelId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: ({ personaId, data }: { personaId: number; data: UpdateThreatPersonaInput }) =>
      api.patch<ThreatPersona>(`/threat-models/${threatModelId}/threat-personas/${personaId}/`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: personaKeys.model(threatModelId) })
      queryClient.invalidateQueries({ queryKey: analysisKeys.all })
    },
  })
}

/** Deleting a persona clears the key on its threats. */
export function useDeleteThreatPersona(threatModelId: string) {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (personaId: number) =>
      api.delete(`/threat-models/${threatModelId}/threat-personas/${personaId}/`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: personaKeys.model(threatModelId) })
      invalidateThreatReaders(queryClient)
    },
  })
}

// ============================================
// Instance-Level Taxonomy Entries
// ============================================

export interface InstanceThreatTaxonomyEntry {
  id: number
  taxonomyEntry: number
  threat: number
  taxonomySlug: string
  taxonomyName: string
  externalId: string
  title: string
  referenceUrl: string
  createdAt: string
  updatedAt: string
}

export function useInstanceTaxonomyEntries(threatId: number | null) {
  return useQuery({
    queryKey: instanceTaxonomyKeys.byThreat(threatId ?? -1),
    queryFn:
      threatId !== null
        ? async () => {
            const response = await api.get<
              { results: InstanceThreatTaxonomyEntry[] } | InstanceThreatTaxonomyEntry[]
            >(`/threat-taxonomy-entries/?threat=${threatId}`)
            return Array.isArray(response) ? response : response.results
          }
        : skipToken,
  })
}

export function useCreateInstanceTaxonomyEntry() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (data: { taxonomyEntry: number; threat: number }) =>
      api.post<InstanceThreatTaxonomyEntry>('/threat-taxonomy-entries/', data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: instanceTaxonomyKeys.all })
      queryClient.invalidateQueries({ queryKey: analysisKeys.all })
    },
  })
}

export function useDeleteInstanceTaxonomyEntry() {
  const queryClient = useQueryClient()

  return useMutation({
    mutationFn: (id: number) => api.delete(`/threat-taxonomy-entries/${id}/`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: instanceTaxonomyKeys.all })
      queryClient.invalidateQueries({ queryKey: analysisKeys.all })
    },
  })
}
