# Generated by Django 5.2.17 on 2026-10-07 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0002_initial'),
        ('threat_models', '0005_remove_outofscopeitem_threat_model_blueprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dfd',
            name='unique_primary_dfd_per_threat_model',
        ),
        migrations.RemoveField(
            model_name='dfd',
            name='threat_model',
        ),
        migrations.AddField(
            model_name='dfd',
            name='blueprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dfds', to='threat_models.blueprint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dfd',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Only the primary DFD of a blueprint syncs nodes to components/threats.'),
        ),
        migrations.AddConstraint(
            model_name='dfd',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('blueprint',), name='unique_primary_dfd_per_blueprint'),
        ),
    ]
