# Generated by Django 5.1.15 on 2026-06-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systems", "0003_category_rename_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataflow",
            name="trust_boundary_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of trust boundary IDs this data flow crosses",
            ),
        ),
    ]
