# Generated by Django 5.2.17 on 2026-10-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_componentlibrary_icon_svg'),
        ('threat_models', '0005_remove_outofscopeitem_threat_model_blueprint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataasset',
            name='threat_model',
        ),
        migrations.RemoveField(
            model_name='orgsystemcomponent',
            name='threat_model',
        ),
        migrations.RemoveField(
            model_name='trustboundary',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='trustzone',
            name='organization',
        ),
        migrations.AddField(
            model_name='dataasset',
            name='blueprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_assets', to='threat_models.blueprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataflow',
            name='blueprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='threat_models.blueprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='blueprint',
            field=models.ForeignKey(default=1, help_text='The structural model this component belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='threat_models.blueprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trustboundary',
            name='blueprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='threat_models.blueprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trustzone',
            name='blueprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='threat_models.blueprint'),
            preserve_default=False,
        ),
    ]
