# Generated by Django 5.2.17 on 2026-10-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_remove_dataasset_threat_model_and_more'),
        ('threat_models', '0005_remove_outofscopeitem_threat_model_blueprint_and_more'),
        ('threats', '0014_remove_componentinstancethreat_dismissal_reason_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrustBoundary',
            new_name='Boundary',
        ),
        migrations.RenameModel(
            old_name='TrustZone',
            new_name='Zone',
        ),
        migrations.RenameModel(
            old_name='DataFlow',
            new_name='Flow',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='crosses_trust_zone',
            new_name='crosses_boundary',
        ),
        migrations.RenameField(
            model_name='orgsystemcomponent',
            old_name='trust_zone',
            new_name='zone',
        ),
        migrations.RenameModel(
            old_name='DataFlowAsset',
            new_name='FlowAsset',
        ),
        migrations.RenameField(
            model_name='flowasset',
            old_name='data_flow',
            new_name='flow',
        ),
    ]
