# Generated by Django 5.2.17 on 2026-10-08 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_rename_trustboundary_boundary_rename_trustzone_zone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boundary',
            options={'ordering': ['zone_a', 'zone_b'], 'verbose_name_plural': 'Boundaries'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name'], 'verbose_name_plural': 'Zones'},
        ),
        migrations.AlterUniqueTogether(
            name='boundary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='boundary',
            name='boundary_type',
            field=models.CharField(choices=[('data', 'data'), ('functional', 'functional'), ('network', 'network'), ('organizational', 'organizational'), ('physical', 'physical'), ('process', 'process'), ('trust', 'trust')], default='trust', help_text='CycloneDX boundary type', max_length=20),
        ),
        migrations.AddField(
            model_name='boundary',
            name='data_transformation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boundary',
            name='protocols',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='boundary',
            name='rate_limit',
            field=models.CharField(blank=True, default='', help_text='Policy text; blank means none', max_length=255),
        ),
        migrations.AddField(
            model_name='boundary',
            name='session_management',
            field=models.JSONField(blank=True, default=dict, help_text="The spec's nine sessionManagement keys"),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(choices=[('availability', 'availability'), ('compliance', 'compliance'), ('data', 'data'), ('deployment', 'deployment'), ('functional', 'functional'), ('geographic', 'geographic'), ('logical', 'logical'), ('network', 'network'), ('organizational', 'organizational'), ('physical', 'physical'), ('process', 'process'), ('tenant', 'tenant'), ('trust', 'trust')], default='trust', help_text='CycloneDX zone type', max_length=20),
        ),
        # A boolean cannot be cast to jsonb; no data exists (D1), so the column
        # is dropped and re-created as the list it now is.
        migrations.RemoveField(
            model_name='boundary',
            name='authentication',
        ),
        migrations.AddField(
            model_name='boundary',
            name='authentication',
            field=models.JSONField(blank=True, default=list),
        ),
        # A boolean cannot be cast to jsonb; no data exists (D1), so the column
        # is dropped and re-created as the list it now is.
        migrations.RemoveField(
            model_name='boundary',
            name='authorization',
        ),
        migrations.AddField(
            model_name='boundary',
            name='authorization',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='format_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='zone',
            name='trust_level',
            field=models.IntegerField(blank=True, help_text='0-100 scale, null when not set', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.RemoveField(
            model_name='boundary',
            name='rate_limiting',
        ),
    ]
