# Generated by Django 5.2.17 on 2026-10-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_alter_boundary_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='authenticated',
        ),
        migrations.AddField(
            model_name='componentlibrary',
            name='kind',
            field=models.CharField(blank=True, choices=[('actor', 'actor'), ('agent', 'agent'), ('api', 'api'), ('broker', 'broker'), ('cache', 'cache'), ('component', 'component'), ('container', 'container'), ('data', 'data'), ('data-store', 'data-store'), ('device', 'device'), ('endpoint', 'endpoint'), ('function', 'function'), ('gateway', 'gateway'), ('infrastructure', 'infrastructure'), ('interface', 'interface'), ('model', 'model'), ('module', 'module'), ('network', 'network'), ('process', 'process'), ('queue', 'queue'), ('resource', 'resource'), ('service', 'service'), ('stream', 'stream'), ('subsystem', 'subsystem'), ('system', 'system'), ('tool', 'tool')], default='', help_text='CycloneDX asset type; blank derives from the category', max_length=30),
        ),
        migrations.AddField(
            model_name='flow',
            name='authentication',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flow',
            name='authorization',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='flow',
            name='flow_type',
            field=models.CharField(choices=[('control', 'control'), ('data', 'data'), ('energy', 'energy'), ('event', 'event'), ('financial', 'financial'), ('message', 'message'), ('physical', 'physical'), ('process', 'process'), ('signal', 'signal')], default='data', help_text='CycloneDX flow type', max_length=20),
        ),
        migrations.AddField(
            model_name='orgsystemcomponent',
            name='kind',
            field=models.CharField(blank=True, choices=[('actor', 'actor'), ('agent', 'agent'), ('api', 'api'), ('broker', 'broker'), ('cache', 'cache'), ('component', 'component'), ('container', 'container'), ('data', 'data'), ('data-store', 'data-store'), ('device', 'device'), ('endpoint', 'endpoint'), ('function', 'function'), ('gateway', 'gateway'), ('infrastructure', 'infrastructure'), ('interface', 'interface'), ('model', 'model'), ('module', 'module'), ('network', 'network'), ('process', 'process'), ('queue', 'queue'), ('resource', 'resource'), ('service', 'service'), ('stream', 'stream'), ('subsystem', 'subsystem'), ('system', 'system'), ('tool', 'tool')], default='', help_text='CycloneDX asset type; copied from the library, editable; blank derives from the category', max_length=30),
        ),
    ]
