# Generated by Django 5.2.17 on 2026-10-08 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_remove_flow_authenticated_componentlibrary_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsystemcomponent',
            name='orgsystem',
            field=models.ForeignKey(blank=True, help_text='The inventory system a system or subsystem asset stands for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='systems.orgsystem'),
        ),
    ]
