"""Where every stored field goes in a TM-BOM document (plan H17).

``FIELD_HOMES`` names, for each model the content digest snapshots, each
field's home: a spec path, a ``precogly:`` property, or ``NOT_EXPORTED`` with
the reason. The coverage test walks the snapshot fields and fails on any
field that is not listed here, so a new field cannot be dropped silently.
"""

NOT_EXPORTED = "not exported"
ROW_LINK = "row link"  # the field is the row's place in a relation, not content


def not_exported(reason: str) -> tuple[str, str]:
    return (NOT_EXPORTED, reason)


FIELD_HOMES: dict[str, dict[str, str | tuple[str, str]]] = {
    "threat_models.ThreatModel": {
        "name": "metadata.component.name",
        "description": "metadata.component.description",
        "criticality": "precogly:criticality",
        "risk_scoring_method": "precogly:risk-scoring-method",
        "format_metadata": "passthrough (document level, kept keys, review block)",
        "methodologies": "threats.methodologies",
        "lifecycle_phase": "metadata.lifecycles, blueprints[].metadata.lifecycles",
        "valid_from": "blueprints[].metadata.validFrom",
        "valid_until": "blueprints[].metadata.validUntil",
        "review_frequency": "blueprints[].metadata.reviewFrequency",
        "owning_team": not_exported("import assigns the importing user's team (#337)"),
        "organization": not_exported("the importing organization owns the copy"),
        "primary_system": "metadata.component (the system asset)",
    },
    "threat_models.Blueprint": {
        "name": "blueprints[].name",
        "description": "blueprints[].description",
        "model_types": "blueprints[].modelTypes",
        "scope_description": "blueprints[].scope.description",
        "format_metadata": "passthrough (kept keys, custom types, scope extras)",
    },
    "threat_models.OutOfScopeItem": {
        "name": "blueprints[].scope.excludedComponents or precogly:out-of-scope",
        "reason": "precogly:out-of-scope",
    },
    "threat_models.Assumption": {
        "blueprint": "blueprints[].assumptions (placement)",
        "description": "assumptions[].description",
        "topic": "assumptions[].topic",
        "validity": "assumptions[].validity",
        "impact": "assumptions[].impact",
        "owner": "assumptions[].owner (party)",
        "owner_name": "assumptions[].owner (party name)",
        "validation_method": "assumptions[].validationMethod",
        "validation_date": "assumptions[].validationDate",
        "format_metadata": "passthrough",
    },
    "threat_models.AssumptionComponent": {
        "assumption": ROW_LINK,
        "component": "assumptions[].relatedAssets",
    },
    "threat_models.BusinessObjective": {
        "name": "businessObjectives[].name",
        "description": "businessObjectives[].description",
        "criticality": "businessObjectives[].criticality",
        "owner": "businessObjectives[].owner (party)",
        "owner_name": "businessObjectives[].owner (party name)",
        "format_metadata": "passthrough",
    },
    "threat_models.UseCase": {
        "name": "useCases[].name",
        "description": "useCases[].description",
        "flow_data": "useCases[] (preconditions, steps, outcomes)",
        "format_metadata": "passthrough",
    },
    "threat_models.ThreatModelRelationship": {
        "target_threat_model": "blueprints[].relationships, externalReferences (G6)",
        "relation_type": "blueprints[].relationships or precogly:relationship",
    },
    "threat_models.ThreatModelFramework": {
        "framework": "standards[] (the frameworks the controls cite)",
    },
    "threat_models.ThreatModelLibraryPack": {
        "library_pack": not_exported(
            "installation detail; import connects every installed pack"
        ),
    },
    "systems.OrgsystemComponent": {
        "blueprint": "blueprints[] (placement)",
        "name": "assets[].name / dataStores[].name",
        "description": "assets[].description / dataStores[].description",
        "category": "precogly:category (data stores are dataStores[])",
        "kind": "assets[].type",
        "actor_type": "precogly:actor-type",
        "data_store_type": "dataStores[].type, precogly:data-store-type",
        "data_sensitivity_level": "precogly:data-sensitivity",
        "component_library": "precogly:library",
        "zone": "assets[].zone / dataStores[].zone",
        "parent_component": "precogly:parent",
        "orgsystem": "metadata.component, precogly:lifecycle-state (F2)",
        "component_type": "precogly:component-type",
        "provider": "precogly:provider / dataStores[].vendor",
        "format_metadata": "passthrough (kept keys, custom types)",
    },
    "systems.Zone": {
        "blueprint": "blueprints[] (placement)",
        "name": "zones[].name",
        "zone_type": "zones[].type",
        "trust_level": "precogly:trust-level",
        "description": "zones[].description",
        "parent": "zones[].parent",
        "format_metadata": "passthrough",
    },
    "systems.Boundary": {
        "blueprint": "blueprints[] (placement)",
        "zone_a": "boundaries[].zones",
        "zone_b": "boundaries[].zones",
        "label": "boundaries[].name",
        "description": "boundaries[].description",
        "boundary_type": "boundaries[].type",
        "authentication": "boundaries[].crossingRequirements.authentication",
        "authorization": "boundaries[].crossingRequirements.authorization",
        "data_validation": "boundaries[].crossingRequirements.dataValidation",
        "data_transformation": "boundaries[].crossingRequirements.dataTransformation",
        "logging": "boundaries[].crossingRequirements.logging",
        "monitoring": "boundaries[].crossingRequirements.monitoring",
        "rate_limit": "boundaries[].crossingRequirements.rateLimit",
        "protocols": "boundaries[].crossingRequirements.protocols",
        "session_management": "boundaries[].sessionManagement",
        "format_metadata": "passthrough",
    },
    "systems.Flow": {
        "blueprint": "blueprints[] (placement)",
        "source_component": "flows[].source",
        "dest_component": "flows[].destination",
        "label": "flows[].name",
        "description": "flows[].description",
        "flow_type": "flows[].type",
        "protocol": "flows[].protocols",
        "port": "precogly:port",
        "encrypted": "flows[].encrypted",
        "authentication": "flows[].authentication",
        "authorization": "flows[].authorization",
        "crosses_boundary": not_exported("derived from the boundary rows (H19)"),
        "has_sensitive_data": "precogly:has-sensitive-data",
        "data_classification": "precogly:data-classification",
        "format_metadata": "passthrough (kept keys, inline data profiles)",
    },
    "systems.FlowAsset": {
        "flow": ROW_LINK,
        "data_asset": "flows[].dataProfiles (the data set's profile ref)",
        "protection_method": "precogly:flow-data",
        "encryption_type": "precogly:flow-data",
        "sensitivity_override": "precogly:flow-data",
        "format": "precogly:flow-data",
    },
    "systems.DataAsset": {
        "blueprint": "blueprints[] (placement)",
        "name": "dataSets[].name",
        "description": "dataSets[].description",
        "classification": "dataSets[].dataProfiles[].classification",
        "confidentiality": "precogly:confidentiality",
        "integrity": "precogly:integrity",
        "availability": "precogly:availability",
        "compliance_tags": "dataSets[].dataProfiles[].regulations",
        "data_sensitivity": "precogly:data-sensitivity-tags",
        "format_metadata": "passthrough",
    },
    "systems.ComponentDataAsset": {
        "component": "dataSets[].placements[].dataStore, dataStores[].dataSets",
        "data_asset": ROW_LINK,
        "data_state": "precogly:placements",
        "volume": "precogly:placements",
        "encrypted": "dataSets[].placements[].encrypted",
    },
    "diagrams.DFD": {
        "blueprint": "blueprints[].visualizations (placement)",
        "name": "visualizations[].name",
        "diagram_type": "visualizations[].type, precogly:diagram-type",
        "is_primary": "precogly:primary",
    },
    "threats.InstanceThreat": {
        "number": "precogly:number",
        "whole_system": "threatScenarios[].affects (the system asset)",
        "threat_library": "threats[].bom-ref (the abstract threat), precogly:library",
        "rating": "threatScenarios[].likelihood and impact",
        "status": "precogly:threat-status",
        "triage_status": "precogly:triage-status",
        "decision_rationale": "precogly:decision-rationale",
        "threat_name": "threatScenarios[].name",
        "threat_description": "threatScenarios[].description",
        "taxonomy_snapshot": "threats[].taxonomies, precogly:taxonomy",
        "impact_description": "precogly:impact-description",
        "actor_persona": "threatScenarios[].actor (persona party)",
        "threat_actor_text": "threatScenarios[].actor, precogly:actor-text",
        "intent": "threatScenarios[].intent",
        "access_level": "threatScenarios[].accessLevel",
        "format_metadata": "passthrough",
    },
    "threats.InstanceThreatTarget": {
        "threat": ROW_LINK,
        "component": "threatScenarios[].affects",
        "flow": "threatScenarios[].affects",
        "zone": "threatScenarios[].affects",
        "boundary": "threatScenarios[].affects",
    },
    "threats.Rating": {
        "methodology": "score.methodology",
        "level": "score.level",
        "score": "score.score",
        "likelihood_level": "likelihood.level",
        "likelihood_score": "likelihood.score",
        "likelihood_factors": "likelihood.factors",
        "likelihood_extra": "likelihood.rationale and extras",
        "impact_level": "impact.level",
        "impact_score": "impact.score",
        "impact_factors": "impact.factors",
        "impact_extra": "impact.categories and extras",
        "rationale": "rationale",
    },
    "threats.InstanceCountermeasure": {
        "number": "precogly:number",
        "countermeasure_library": "precogly:library",
        "status": "controls[].status",
        "verified_by": "precogly:verified-by",
        "evidence_url": "controls[].evidence",
        "required_for_release": "precogly:required-for-release",
        "assigned_owner": "controls[].owner (party)",
        "countermeasure_name": "controls[].name",
        "countermeasure_description": "controls[].description",
        "control_functions": "controls[].category, precogly:control-functions",
        "control_nature": "precogly:control-nature",
        "effectiveness": "controls[].effectiveness",
        "priority": "precogly:priority",
        "due_date": "precogly:due-date",
        "external_ticket_url": "controls[].externalReferences",
        "implemented_by_party": "controls[].implementedBy (provider party)",
        "source": "precogly:source",
        "format_metadata": "passthrough",
    },
    "threats.InstanceCountermeasureTarget": {
        "countermeasure": ROW_LINK,
        "component": "controls[].appliesTo",
        "flow": "controls[].appliesTo",
        "zone": "controls[].appliesTo",
        "boundary": "controls[].appliesTo",
    },
    "threats.InstanceCountermeasureProvider": {
        "countermeasure": ROW_LINK,
        "component": "controls[].implementedBy",
    },
    "threats.CountermeasureThreatLink": {
        "countermeasure": "threatScenarios[].mitigations, precogly:mitigates",
        "threat": ROW_LINK,
    },
    "threats.InstanceCountermeasureStandard": {
        "countermeasure": ROW_LINK,
        "requirement": "controls[].requirements (standards[] catalogue)",
        "sufficiency": "precogly:sufficiency",
        "section_code": "standards[].requirements[].identifier",
        "framework_name": "standards[].name",
        "requirement_description": "standards[].requirements[].text",
    },
    "threats.InstanceThreatTaxonomyEntry": {
        "taxonomy_entry": "threats[].taxonomies, precogly:instance-categories",
        "threat": ROW_LINK,
    },
    "threats.ThreatSourceLink": {
        "source": "threats[].origin, precogly:threat-sources",
        "threat": ROW_LINK,
    },
    "threats.InstanceThreatBusinessObjective": {
        "threat": ROW_LINK,
        "business_objective": "precogly:business-objectives",
    },
    "threats.ThreatPersona": {
        "symbolic_name": "precogly:persona-symbolic-name",
        "name": "actors[].name, precogly:persona-name",
        "description": "actors[].description",
        "is_person": "precogly:persona-is-person",
        "malicious_intent": "precogly:persona-malicious-intent",
        "skill_level": "precogly:persona-skill-level",
        "motivation": "precogly:persona-motivation",
        "resources": "precogly:persona-resources",
        "objectives": "precogly:persona-objectives",
        "format_metadata": "passthrough",
    },
    "threats.Risk": {
        "name": "risks[].name",
        "description": "risks[].description",
        "status": "risks[].status",
        "statement": "risks[].statement",
        "inherent": "risks[].inherentRisk",
        "residual": "risks[].residualRisk",
        "target": "risks[].targetRisk",
        "domains": "risks[].domains",
        "owner": "risks[].owner (party)",
        "assigned_to": "precogly:assigned-to",
        "format_metadata": "passthrough",
    },
    "threats.RiskThreat": {
        "risk": ROW_LINK,
        "threat": "risks[].relatedThreats",
    },
    "threats.RiskBusinessObjective": {
        "risk": ROW_LINK,
        "business_objective": "risks[].relatedBusinessObjectives",
    },
    "threats.RiskResponse": {
        "risk": ROW_LINK,
        "strategy": "risks[].responses[].strategy",
        "description": "risks[].responses[].description",
        "status": "risks[].responses[].status",
        "effectiveness": "risks[].responses[].effectiveness",
        "cost": "risks[].responses[].cost",
        "priority": "risks[].responses[].priority",
        "owner": "risks[].responses[].owner (party)",
        "target_date": "risks[].responses[].targetDate",
        "format_metadata": "passthrough",
    },
    "threats.RiskResponseCountermeasure": {
        "response": ROW_LINK,
        "countermeasure": "risks[].responses[].controls",
    },
}
