import { describe, it, expect } from 'vitest'
import { buildAnalysisTree, type AnalysisTreeInput } from '../components/threat-analysis/hierarchy-utils'
import type { AnalysisThreat, AnalysisTarget, AnalysisCountermeasure } from '../types/threat-analysis'

function target(type: AnalysisTarget['type'], id: number, name = `${type} ${id}`): AnalysisTarget {
  return { type, id, name, blueprintId: 1, nodeId: null, edgeId: null, dfdId: null, dfdName: null }
}

function countermeasure(status: AnalysisCountermeasure['status']): AnalysisCountermeasure {
  return {
    id: `cm-${Math.random()}`,
    countermeasureId: 'custom',
    componentThreatId: '',
    status,
    createdAt: '',
    updatedAt: '',
  }
}

function threat(
  number: number,
  targets: AnalysisTarget[],
  options: Partial<AnalysisThreat> = {}
): AnalysisThreat {
  return {
    id: `threat-${number}`,
    diagramId: '',
    threatId: 'custom',
    triageStatus: 'open',
    countermeasures: [],
    createdAt: '',
    updatedAt: '',
    backendThreatId: number,
    number,
    displayNumber: `T${number}`,
    wholeSystem: targets.length === 0,
    targets,
    autoGenerated: false,
    libraryMismatch: false,
    threatName: `Threat ${number}`,
    rating: null,
    ...options,
  }
}

const baseInput: AnalysisTreeInput = {
  blueprints: [{ id: 1, name: 'Main' }],
  zones: [
    { id: 10, name: 'Control Network', blueprint: 1, parent: null, zoneType: 'network' },
    { id: 11, name: 'PLC rack', blueprint: 1, parent: 10, zoneType: 'physical' },
  ],
  components: [
    { id: 100, name: 'PLC', blueprint: 1, zone: 11, parentComponent: null },
    { id: 101, name: 'Field sensor', blueprint: 1, zone: 10, parentComponent: null },
    { id: 102, name: 'Historian', blueprint: 1, zone: null, parentComponent: null },
    { id: 103, name: 'Historian DB', blueprint: 1, zone: null, parentComponent: 102 },
  ],
  flows: [{ id: 200, blueprint: 1, label: 'Control signals' }],
  boundaries: [{ id: 300, blueprint: 1, label: '', zoneAName: 'Control Network', zoneBName: 'DMZ' }],
  threats: [],
}

describe('buildAnalysisTree', () => {
  it('nests zones by parent, components in their zone, and components under their parent component', () => {
    const { root, byKey } = buildAnalysisTree(baseInput)

    expect(root.kind).toBe('system')
    expect(root.children.map((node) => node.key)).toEqual([
      'zone-10',
      'component-102',
      'flows-1',
      'boundaries-1',
    ])

    const controlNetwork = byKey.get('zone-10')!
    expect(controlNetwork.children.map((node) => node.key)).toEqual(['zone-11', 'component-101'])
    expect(byKey.get('zone-11')!.children.map((node) => node.key)).toEqual(['component-100'])
    expect(byKey.get('zone-11')!.depth).toBe(2)

    const historian = byKey.get('component-102')!
    expect(historian.children.map((node) => node.key)).toEqual(['component-103'])

    expect(byKey.get('flows-1')!.selection).toBeNull()
    expect(byKey.get('flow-200')!.label).toBe('Control signals')
    expect(byKey.get('boundary-300')!.label).toBe('Control Network | DMZ')
  })

  it('shows the blueprint level only when the model has more than one blueprint', () => {
    const single = buildAnalysisTree(baseInput)
    expect(single.root.children.some((node) => node.kind === 'blueprint')).toBe(false)

    const two = buildAnalysisTree({
      ...baseInput,
      blueprints: [
        { id: 1, name: 'Main', displayOrder: 0 },
        { id: 2, name: 'Second', displayOrder: 1 },
      ],
      components: [...baseInput.components, { id: 104, name: 'Other', blueprint: 2, zone: null, parentComponent: null }],
    })
    expect(two.root.children.map((node) => node.key)).toEqual(['blueprint-1', 'blueprint-2'])
    expect(two.byKey.get('blueprint-2')!.children.map((node) => node.key)).toEqual(['component-104'])
    expect(two.byKey.get('blueprint-1')!.children.map((node) => node.key)).toContain('zone-10')
  })

  it('places whole-system threats on the System root and counts only those there', () => {
    const { root, byKey } = buildAnalysisTree({
      ...baseInput,
      threats: [threat(1, []), threat(2, [target('component', 100)])],
    })
    expect(root.directThreatIds).toEqual(new Set(['threat-1']))
    expect(root.counts.total).toBe(1)
    expect(byKey.get('component-100')!.counts.total).toBe(1)
  })

  it('counts a shared threat once at every level above its targets', () => {
    const shared = threat(7, [target('component', 100), target('flow', 200), target('zone', 10)], {
      countermeasures: [countermeasure('gap')],
    })
    const plcOnly = threat(9, [target('component', 100)], { countermeasures: [countermeasure('verified')] })
    const { byKey } = buildAnalysisTree({ ...baseInput, threats: [shared, plcOnly] })

    expect(byKey.get('component-100')!.counts).toEqual({ total: 2, exposed: 1, addressable: 0, mitigated: 1 })
    expect(byKey.get('flow-200')!.counts.total).toBe(1)
    // The zone holds T7 directly and through the PLC: still one.
    const zone = byKey.get('zone-10')!
    expect(zone.directThreatIds).toEqual(new Set(['threat-7']))
    expect(zone.counts).toEqual({ total: 2, exposed: 1, addressable: 0, mitigated: 1 })
    expect(byKey.get('flows-1')!.counts.total).toBe(1)
  })

  it('leaves triaged threats out of the counts', () => {
    const { byKey } = buildAnalysisTree({
      ...baseInput,
      threats: [threat(3, [target('component', 100)], { triageStatus: 'accept' })],
    })
    expect(byKey.get('component-100')!.counts.total).toBe(0)
  })

  it('does not loop on a parent cycle', () => {
    const { byKey } = buildAnalysisTree({
      ...baseInput,
      zones: [
        { id: 1, name: 'A', blueprint: 1, parent: 2 },
        { id: 2, name: 'B', blueprint: 1, parent: 1 },
      ],
      components: [],
    })
    expect(byKey.has('zone-1')).toBe(true)
    expect(byKey.has('zone-2')).toBe(true)
  })
})
