# Generated by Django 5.2.17 on 2026-10-07 23:25

import apps.threat_models.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # Runs after every migration that predates it in the other apps: their data
    # migrations (threats 0009, for one) build historical querysets over the
    # `threat_model` keys this step removes, and Django resolves historical
    # models from the graph state at the moment each migration runs.
    dependencies = [
        ('threat_models', '0004_cyclonedx_schema_enrichment'),
        ('threats', '0014_remove_componentinstancethreat_dismissal_reason_and_more'),
        ('systems', '0006_componentlibrary_icon_svg'),
        ('diagrams', '0002_initial'),
        ('compliance', '0005_alter_countermeasurelibrarystandard_requirement_and_more'),
        ('packs', '0002_pendingtaxonomyoverlay'),
        ('ai', '0002_aiusagerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outofscopeitem',
            name='threat_model',
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model_types', models.JSONField(blank=True, default=apps.threat_models.models.default_model_types, help_text='CycloneDX model types this blueprint represents; at least one')),
                ('scope_description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='threat_models.threatmodel')),
            ],
            options={
                'ordering': ['display_order', 'created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='outofscopeitem',
            name='blueprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='out_of_scope_items', to='threat_models.blueprint'),
            preserve_default=False,
        ),
    ]
