# Generated by Django 5.2.17 on 2026-10-07 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_models', '0005_remove_outofscopeitem_threat_model_blueprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_threat_number', models.PositiveIntegerField(default=1)),
                ('next_countermeasure_number', models.PositiveIntegerField(default=1)),
                ('threat_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='threat_models.threatmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
