# Generated by Django 5.2.17 on 2026-10-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_models', '0006_threatmodelstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatmodel',
            name='risk_scoring_method',
            field=models.CharField(choices=[('qualitative-matrix', 'Likelihood x Impact (5x5 Matrix)'), ('owasp-risk-rating', 'OWASP Risk Rating'), ('fair', 'FAIR'), ('mozilla-rra', 'Mozilla Rapid Risk Assessment')], default='qualitative-matrix', help_text='Scoring methodology used for all risks in this threat model', max_length=20),
        ),
    ]
