# Generated by Django 5.2.17 on 2026-10-08 03:49

import apps.threat_models.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_remove_flow_authenticated_componentlibrary_kind_and_more'),
        ('threat_models', '0007_alter_threatmodel_risk_scoring_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatmodel',
            name='assumptions',
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='methodologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=apps.threat_models.models.default_methodologies, size=None),
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('topic', models.CharField(blank=True, choices=[('availability', 'availability'), ('business', 'business'), ('compliance', 'compliance'), ('operational', 'operational'), ('performance', 'performance'), ('security', 'security'), ('technical', 'technical')], default='', max_length=20)),
                ('validity', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('invalid', 'Invalid'), ('unknown', 'Unknown')], default='unverified', max_length=20)),
                ('impact', models.TextField(blank=True, default='')),
                ('owner_name', models.CharField(blank=True, default='', help_text='An owner who is not a user', max_length=255)),
                ('validation_method', models.TextField(blank=True, default='')),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='threat_models.blueprint')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assumptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('criticality', models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=20)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business_objectives', to=settings.AUTH_USER_MODEL)),
                ('threat_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_objectives', to='threat_models.threatmodel')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssumptionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('assumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_links', to='threat_models.assumption')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumption_links', to='systems.orgsystemcomponent')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('assumption', 'component'), name='unique_assumption_component')],
            },
        ),
    ]
