# Generated by Django 5.2.17 on 2026-10-08 04:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_models', '0008_remove_threatmodel_assumptions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatmodel',
            name='scope_locked',
        ),
        migrations.RemoveField(
            model_name='threatmodel',
            name='scope_locked_at',
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='lifecycle_phase',
            field=models.CharField(blank=True, choices=[('design', 'design'), ('pre-build', 'pre-build'), ('build', 'build'), ('post-build', 'post-build'), ('operations', 'operations'), ('discovery', 'discovery'), ('decommission', 'decommission')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='review_frequency',
            field=models.CharField(blank=True, default='', help_text='ISO 8601 duration, e.g. P6M', max_length=40, validators=[django.core.validators.RegexValidator('^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?$', 'Use an ISO 8601 duration of years, months, weeks or days, such as P6M.')]),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ThreatModelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_digest', models.CharField(blank=True, default='', max_length=64)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_threat_models', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_threat_models', to=settings.AUTH_USER_MODEL)),
                ('threat_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='threat_models.threatmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
