# Generated by Django 5.2.17 on 2026-10-08 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_alter_orgsystemcomponent_orgsystem'),
        ('threat_models', '0009_remove_threatmodel_scope_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatmodel',
            name='primary_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='primary_threat_models', to='systems.orgsystem'),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='serial_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='threatmodelstate',
            name='export_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='threatmodelstate',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ThreatModelOrgsystem',
        ),
    ]
