# Generated by Django 5.1.15 on 2026-09-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0014_remove_componentinstancethreat_dismissal_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancecountermeasure',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('vault_import', 'Vault Import'), ('pentest', 'Pentest')], default='manual', help_text='Where this countermeasure instance originated', max_length=20),
        ),
    ]
