# Generated by Django 5.2.17 on 2026-10-07 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_rename_trustboundary_boundary_rename_trustzone_zone_and_more'),
        ('threat_models', '0006_threatmodelstate'),
        ('threats', '0014_remove_componentinstancethreat_dismissal_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(help_text='Unique within the threat model, assigned once, never reused (T7 is 7)')),
                ('whole_system', models.BooleanField(default=False, help_text='True: applies to the whole system and has no targets')),
                ('auto_generated', models.BooleanField(default=False, help_text='Set by library generation, cleared on the first user edit')),
                ('inherent_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('residual_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('exposed', 'Exposed'), ('addressable', 'Addressable'), ('mitigated', 'Mitigated')], default='exposed', max_length=20)),
                ('severity_scoring_metadata', models.JSONField(blank=True, default=dict)),
                ('triage_status', models.CharField(choices=[('open', 'Open'), ('accept', 'Accept'), ('mitigate', 'Mitigate'), ('delegate', 'Delegate'), ('eliminate', 'Eliminate')], default='open', max_length=20)),
                ('decision_rationale', models.TextField(blank=True, default='', help_text='Rationale for triage decision (recommended for accept/delegate/eliminate)')),
                ('format_metadata', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('threat_name', models.CharField(blank=True, help_text='Copied from ThreatLibrary.name on creation', max_length=255)),
                ('threat_description', models.TextField(blank=True, help_text='Copied from ThreatLibrary.description on creation')),
                ('taxonomy_snapshot', models.JSONField(blank=True, default=list, help_text='Snapshot of taxonomy entries at creation time')),
                ('impact_description', models.TextField(blank=True, default='', help_text='Narrative description of what the attacker achieves')),
                ('threat_actor_text', models.CharField(blank=True, default='', help_text="Free-text threat actor (e.g. 'state actor', 'hacktivist')", max_length=100)),
                ('intent', models.CharField(blank=True, choices=[('accidental', 'Accidental'), ('opportunistic', 'Opportunistic'), ('targeted', 'Targeted'), ('persistent', 'Persistent')], default='', help_text='Attacker intent: accidental, opportunistic, targeted, or persistent', max_length=20)),
                ('access_level', models.CharField(blank=True, choices=[('none', 'None'), ('external', 'External'), ('internal', 'Internal'), ('privileged', 'Privileged'), ('physical', 'Physical')], default='', help_text='Access level required: none, external, internal, privileged, or physical', max_length=20)),
            ],
            options={
                'ordering': ['display_order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InstanceThreatTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        # Drop the old exclusive-FK constraints before the columns they reference go;
        # Postgres drops a check constraint with its column, so the reverse order fails.
        migrations.RemoveConstraint(
            model_name='countermeasurethreatlink',
            name='cm_link_exactly_one_threat_fk',
        ),
        migrations.RemoveConstraint(
            model_name='countermeasurethreatlink',
            name='unique_cm_component_threat_link',
        ),
        migrations.RemoveConstraint(
            model_name='countermeasurethreatlink',
            name='unique_cm_flow_threat_link',
        ),
        migrations.RemoveConstraint(
            model_name='instancethreattaxonomyentry',
            name='taxonomy_link_exactly_one_fk',
        ),
        migrations.RemoveConstraint(
            model_name='instancethreattaxonomyentry',
            name='unique_taxonomy_component_threat',
        ),
        migrations.RemoveConstraint(
            model_name='instancethreattaxonomyentry',
            name='unique_taxonomy_flow_threat',
        ),
        migrations.RemoveConstraint(
            model_name='riskthreat',
            name='risk_threat_exactly_one_fk',
        ),
        migrations.RemoveConstraint(
            model_name='riskthreat',
            name='unique_risk_component_threat',
        ),
        migrations.RemoveConstraint(
            model_name='riskthreat',
            name='unique_risk_flow_threat',
        ),
        migrations.RemoveConstraint(
            model_name='threatsourcelink',
            name='source_link_exactly_one_fk',
        ),
        migrations.RemoveConstraint(
            model_name='threatsourcelink',
            name='unique_source_component_threat',
        ),
        migrations.RemoveConstraint(
            model_name='threatsourcelink',
            name='unique_source_flow_threat',
        ),
        migrations.AlterUniqueTogether(
            name='componentinstancethreat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='componentinstancethreat',
            name='component',
        ),
        migrations.RemoveField(
            model_name='componentinstancethreat',
            name='threat_library',
        ),
        migrations.RemoveField(
            model_name='instancethreattaxonomyentry',
            name='component_threat',
        ),
        migrations.RemoveField(
            model_name='threatsourcelink',
            name='component_threat',
        ),
        migrations.RemoveField(
            model_name='riskthreat',
            name='component_threat',
        ),
        migrations.RemoveField(
            model_name='countermeasurethreatlink',
            name='component_threat',
        ),
        migrations.RemoveField(
            model_name='threatpersonalink',
            name='component_threat',
        ),
        migrations.AlterUniqueTogether(
            name='dataflowinstancethreat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dataflowinstancethreat',
            name='data_flow',
        ),
        migrations.RemoveField(
            model_name='dataflowinstancethreat',
            name='threat_library',
        ),
        migrations.RemoveField(
            model_name='riskthreat',
            name='flow_threat',
        ),
        migrations.RemoveField(
            model_name='instancethreattaxonomyentry',
            name='flow_threat',
        ),
        migrations.RemoveField(
            model_name='threatsourcelink',
            name='flow_threat',
        ),
        migrations.RemoveField(
            model_name='countermeasurethreatlink',
            name='flow_threat',
        ),
        migrations.RemoveField(
            model_name='threatpersonalink',
            name='flow_threat',
        ),
        migrations.RemoveField(
            model_name='threatpersonalink',
            name='persona',
        ),
        migrations.AddField(
            model_name='instancecountermeasure',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Set by library generation, cleared on the first user edit'),
        ),
        migrations.AddField(
            model_name='instancethreat',
            name='actor_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threats', to='threats.threatpersona'),
        ),
        migrations.AddField(
            model_name='instancethreat',
            name='threat_library',
            field=models.ForeignKey(blank=True, help_text='Null means orphaned/custom threat (library item was removed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='threats.threatlibrary'),
        ),
        migrations.AddField(
            model_name='instancethreat',
            name='threat_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='threat_models.threatmodel'),
        ),
        migrations.AddField(
            model_name='countermeasurethreatlink',
            name='threat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countermeasure_links', to='threats.instancethreat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancethreattaxonomyentry',
            name='threat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instance_taxonomy_links', to='threats.instancethreat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskthreat',
            name='threat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='threats.instancethreat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatsourcelink',
            name='threat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='threats.instancethreat'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='countermeasurethreatlink',
            constraint=models.UniqueConstraint(fields=('countermeasure', 'threat'), name='unique_cm_threat_link'),
        ),
        migrations.AddConstraint(
            model_name='instancethreattaxonomyentry',
            constraint=models.UniqueConstraint(fields=('taxonomy_entry', 'threat'), name='unique_taxonomy_threat'),
        ),
        migrations.AddConstraint(
            model_name='riskthreat',
            constraint=models.UniqueConstraint(fields=('risk', 'threat'), name='unique_risk_threat'),
        ),
        migrations.AddConstraint(
            model_name='threatsourcelink',
            constraint=models.UniqueConstraint(fields=('source', 'threat'), name='unique_source_threat'),
        ),
        migrations.AddField(
            model_name='instancethreattarget',
            name='boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_targets', to='systems.boundary'),
        ),
        migrations.AddField(
            model_name='instancethreattarget',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_targets', to='systems.orgsystemcomponent'),
        ),
        migrations.AddField(
            model_name='instancethreattarget',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_targets', to='systems.flow'),
        ),
        migrations.AddField(
            model_name='instancethreattarget',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='threats.instancethreat'),
        ),
        migrations.AddField(
            model_name='instancethreattarget',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_targets', to='systems.zone'),
        ),
        migrations.DeleteModel(
            name='ComponentInstanceThreat',
        ),
        migrations.DeleteModel(
            name='DataFlowInstanceThreat',
        ),
        migrations.DeleteModel(
            name='ThreatPersonaLink',
        ),
        migrations.AddConstraint(
            model_name='instancethreat',
            constraint=models.UniqueConstraint(fields=('threat_model', 'number'), name='unique_threat_number_per_model'),
        ),
        migrations.AddConstraint(
            model_name='instancethreat',
            constraint=models.CheckConstraint(condition=models.Q(('actor_persona__isnull', True), ('threat_actor_text', ''), _connector='OR'), name='threat_actor_persona_or_text'),
        ),
        migrations.AddConstraint(
            model_name='instancethreattarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component__isnull', False), ('flow__isnull', True), ('zone__isnull', True), ('boundary__isnull', True)), models.Q(('flow__isnull', False), ('component__isnull', True), ('zone__isnull', True), ('boundary__isnull', True)), models.Q(('zone__isnull', False), ('component__isnull', True), ('flow__isnull', True), ('boundary__isnull', True)), models.Q(('boundary__isnull', False), ('component__isnull', True), ('flow__isnull', True), ('zone__isnull', True)), _connector='OR'), name='threat_target_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='instancethreattarget',
            constraint=models.UniqueConstraint(condition=models.Q(('component__isnull', False)), fields=('threat', 'component'), name='threat_target_unique_component'),
        ),
        migrations.AddConstraint(
            model_name='instancethreattarget',
            constraint=models.UniqueConstraint(condition=models.Q(('flow__isnull', False)), fields=('threat', 'flow'), name='threat_target_unique_flow'),
        ),
        migrations.AddConstraint(
            model_name='instancethreattarget',
            constraint=models.UniqueConstraint(condition=models.Q(('zone__isnull', False)), fields=('threat', 'zone'), name='threat_target_unique_zone'),
        ),
        migrations.AddConstraint(
            model_name='instancethreattarget',
            constraint=models.UniqueConstraint(condition=models.Q(('boundary__isnull', False)), fields=('threat', 'boundary'), name='threat_target_unique_boundary'),
        ),
    ]
