# Generated by Django 5.2.17 on 2026-10-08 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_rename_trustboundary_boundary_rename_trustzone_zone_and_more'),
        ('threat_models', '0006_threatmodelstate'),
        ('threats', '0015_instancethreat_instancethreattarget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceCountermeasureProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InstanceCountermeasureTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='instancecountermeasure',
            name='inherited_from_component_name',
        ),
        migrations.RemoveField(
            model_name='instancecountermeasure',
            name='inherited_from_zone_name',
        ),
        migrations.RemoveField(
            model_name='instancecountermeasure',
            name='is_inherited',
        ),
        migrations.AddField(
            model_name='instancecountermeasure',
            name='implemented_by_party',
            field=models.CharField(blank=True, default='', help_text='The provider that implements the control, as text (until a party model exists)', max_length=255),
        ),
        migrations.AddField(
            model_name='instancecountermeasure',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='Unique within the threat model, assigned once, never reused (C3 is 3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instancecountermeasure',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Where the control came from: a compliance tool, a pentest, a vendor list', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='instancecountermeasure',
            constraint=models.UniqueConstraint(fields=('threat_model', 'number'), name='unique_countermeasure_number_per_model'),
        ),
        migrations.AddField(
            model_name='instancecountermeasureprovider',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implemented_countermeasure_links', to='systems.orgsystemcomponent'),
        ),
        migrations.AddField(
            model_name='instancecountermeasureprovider',
            name='countermeasure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='threats.instancecountermeasure'),
        ),
        migrations.AddField(
            model_name='instancecountermeasuretarget',
            name='boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_targets', to='systems.boundary'),
        ),
        migrations.AddField(
            model_name='instancecountermeasuretarget',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_targets', to='systems.orgsystemcomponent'),
        ),
        migrations.AddField(
            model_name='instancecountermeasuretarget',
            name='countermeasure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='threats.instancecountermeasure'),
        ),
        migrations.AddField(
            model_name='instancecountermeasuretarget',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_targets', to='systems.flow'),
        ),
        migrations.AddField(
            model_name='instancecountermeasuretarget',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_targets', to='systems.zone'),
        ),
        migrations.AddConstraint(
            model_name='instancecountermeasureprovider',
            constraint=models.UniqueConstraint(fields=('countermeasure', 'component'), name='unique_countermeasure_provider'),
        ),
        migrations.AddConstraint(
            model_name='instancecountermeasuretarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component__isnull', False), ('flow__isnull', True), ('zone__isnull', True), ('boundary__isnull', True)), models.Q(('flow__isnull', False), ('component__isnull', True), ('zone__isnull', True), ('boundary__isnull', True)), models.Q(('zone__isnull', False), ('component__isnull', True), ('flow__isnull', True), ('boundary__isnull', True)), models.Q(('boundary__isnull', False), ('component__isnull', True), ('flow__isnull', True), ('zone__isnull', True)), _connector='OR'), name='countermeasure_target_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='instancecountermeasuretarget',
            constraint=models.UniqueConstraint(condition=models.Q(('component__isnull', False)), fields=('countermeasure', 'component'), name='countermeasure_target_unique_component'),
        ),
        migrations.AddConstraint(
            model_name='instancecountermeasuretarget',
            constraint=models.UniqueConstraint(condition=models.Q(('flow__isnull', False)), fields=('countermeasure', 'flow'), name='countermeasure_target_unique_flow'),
        ),
        migrations.AddConstraint(
            model_name='instancecountermeasuretarget',
            constraint=models.UniqueConstraint(condition=models.Q(('zone__isnull', False)), fields=('countermeasure', 'zone'), name='countermeasure_target_unique_zone'),
        ),
        migrations.AddConstraint(
            model_name='instancecountermeasuretarget',
            constraint=models.UniqueConstraint(condition=models.Q(('boundary__isnull', False)), fields=('countermeasure', 'boundary'), name='countermeasure_target_unique_boundary'),
        ),
    ]
