# Generated by Django 5.2.17 on 2026-10-08 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_fix_business_unit_code_optional'),
        ('threats', '0016_instancecountermeasureprovider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='componentlibrarythreat',
            name='default_severity',
        ),
        migrations.RemoveField(
            model_name='instancethreat',
            name='inherent_severity',
        ),
        migrations.RemoveField(
            model_name='instancethreat',
            name='residual_severity',
        ),
        migrations.RemoveField(
            model_name='instancethreat',
            name='severity_scoring_metadata',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='inherent_level',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='inherent_score',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='residual_level',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='residual_score',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='scoring_metadata',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='target_level',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='target_score',
        ),
        migrations.AddField(
            model_name='componentlibrarythreat',
            name='default_level',
            field=models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Level of the generated scenario (CycloneDX riskScore.level)', max_length=20),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('methodology', models.CharField(help_text='CycloneDX methodology value, or a custom name', max_length=40)),
                ('level', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('score', models.FloatField(blank=True, db_index=True, null=True)),
                ('likelihood_level', models.CharField(blank=True, choices=[('very-low', 'Very low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very-high', 'Very high'), ('certain', 'Certain')], max_length=10)),
                ('likelihood_score', models.FloatField(blank=True, null=True)),
                ('likelihood_factors', models.JSONField(blank=True, default=list)),
                ('likelihood_extra', models.JSONField(blank=True, default=dict)),
                ('impact_level', models.CharField(blank=True, choices=[('negligible', 'Negligible'), ('low', 'Low'), ('moderate', 'Moderate'), ('major', 'Major'), ('catastrophic', 'Catastrophic')], max_length=12)),
                ('impact_score', models.FloatField(blank=True, null=True)),
                ('impact_factors', models.JSONField(blank=True, default=list)),
                ('impact_extra', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='instancethreat',
            name='rating',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='threats.rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='inherent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='threats.rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='residual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='threats.rating'),
        ),
        migrations.AddField(
            model_name='risk',
            name='target',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='threats.rating'),
        ),
    ]
