# Generated by Django 5.2.17 on 2026-10-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0017_alter_risk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentlibrarythreat',
            name='flow_types',
            field=models.JSONField(blank=True, default=list, help_text="Flow types the link applies to; empty means data-like flows only, 'any' means all"),
        ),
    ]
