# Generated by Django 5.2.17 on 2026-10-08 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0018_componentlibrarythreat_flow_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='response',
        ),
        migrations.AddField(
            model_name='risk',
            name='statement',
            field=models.TextField(blank=True, default='', help_text='Source, event and impact in one sentence'),
        ),
        migrations.AddField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('identified', 'Identified'), ('assessed', 'Assessed'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('transferred', 'Transferred'), ('retired', 'Retired')], default='identified', max_length=20),
        ),
        migrations.AlterField(
            model_name='riskresponse',
            name='cost',
            field=models.CharField(blank=True, choices=[('trivial', 'Trivial'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('extreme', 'Extreme')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='riskresponse',
            name='priority',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='RiskResponseCountermeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('countermeasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_response_links', to='threats.instancecountermeasure')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countermeasure_links', to='threats.riskresponse')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('response', 'countermeasure'), name='unique_risk_response_countermeasure')],
            },
        ),
    ]
