# Generated by Django 5.2.17 on 2026-10-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_models', '0008_remove_threatmodel_assumptions_and_more'),
        ('threats', '0019_remove_risk_response_risk_statement_risk_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceThreatBusinessObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('business_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_links', to='threat_models.businessobjective')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_objective_links', to='threats.instancethreat')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('threat', 'business_objective'), name='unique_threat_business_objective')],
            },
        ),
        migrations.CreateModel(
            name='RiskBusinessObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('business_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='threat_models.businessobjective')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_objective_links', to='threats.risk')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('risk', 'business_objective'), name='unique_risk_business_objective')],
            },
        ),
    ]
